# Generated by Django 5.2.10 on 2026-01-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Javascript', 'Javascript')], default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=100),
        ),
    ]
