# Generated by Django 5.2.10 on 2026-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_student_address_student_age_student_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('representative_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('AI and Data Science', 'AI and Data Science'), ('Game Development', 'Game Development')], default=''),
        ),
    ]
