# Generated by Django 5.2.10 on 2026-01-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_company_alter_student_age_alter_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company_placed_in',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orgs.company'),
        ),
    ]
