# Generated by Django 5.2.10 on 2026-01-24 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_student_company_placed_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=400)),
                ('ctc', models.IntegerField(default=0)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orgs.company')),
            ],
        ),
    ]
