# Generated by Django 5.2.10 on 2026-01-24 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_late', models.BooleanField(default='')),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('redflagged', models.BooleanField(default='')),
                ('assignment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orgs.assignment')),
                ('similarity_with', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_link', to='orgs.student')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orgs.student')),
            ],
        ),
    ]
