# Generated by Django 5.2.10 on 2026-01-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_assignmentssubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentssubmitted',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentssubmitted',
            name='similarity_with',
        ),
        migrations.RemoveField(
            model_name='assignmentssubmitted',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentsSubmitted',
        ),
    ]
