# Generated by Django 5.2.10 on 2026-01-24 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0007_remove_assignmentssubmitted_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=400)),
                ('ctc', models.IntegerField(default=0)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orgs.company')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_late', models.BooleanField(default='')),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('redflagged', models.BooleanField(default='')),
                ('assignment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('similarity_with', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_link', to='orgs.student')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orgs.student')),
            ],
        ),
    ]
