# Generated by Django 5.2.10 on 2026-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentssubmitted_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
