# Generated by Django 5.2.10 on 2026-01-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignmentssubmitted_similarity_and_more'),
        ('orgs', '0008_alter_student_email_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='is_late',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='redflagged',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='similarity_with',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_link', to='orgs.student'),
        ),
    ]
