# Generated by Django 5.2.10 on 2026-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignmentssubmitted_is_late_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='redflagged',
            field=models.BooleanField(default=False),
        ),
    ]
