# Generated by Django 5.2.10 on 2026-01-29 12:38

import assignments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignmentssubmitted_is_late_and_more'),
        ('orgs', '0008_alter_student_email_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='similarity_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_link', to='orgs.student'),
        ),
        migrations.AlterField(
            model_name='assignmentssubmitted',
            name='uploaded_file',
            field=models.FileField(upload_to=assignments.models.unique_file_name),
        ),
    ]
