# Generated by Django 5.2.10 on 2026-01-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_assignmentssubmitted_similarity_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentssubmitted',
            name='uploaded_file',
        ),
    ]
