# Generated by Django 5.2.10 on 2026-01-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignmentssubmitted_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentssubmitted',
            name='chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
